[theme]
base = "light"
primaryColor = "#1769E0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7FAFC"
textColor = "#243B53"
font = "sans-serif"

[server]
maxUploadSize = 20
headless = true

[browser]
gatherUsageStats = false
